import { type Tables } from "../db/database.types.ts";

// --- ENTITIES ---

/**
 * Represents the core `flashcards` table entity.
 * All other DTOs and Command Models are derived from this type.
 */
export type Flashcard = Tables<"flashcards">;

// --- DTOs (Data Transfer Objects) ---

/**
 * DTO for a flashcard that has been generated by the AI but not yet saved.
 * Used in the response of `POST /api/flashcards/generate`.
 */
export type GeneratedFlashcardDto = Pick<Flashcard, "question" | "answer">;

/**
 * DTO for a complete flashcard record.
 * Used in the response of `POST /api/flashcards` after a new card is created.
 */
export type FlashcardDto = Flashcard;

/**
 * DTO for a flashcard item in a list.
 * Contains a subset of fields for summary views.
 * Used in the response of `GET /api/flashcards`.
 */
export type FlashcardListItemDto = Pick<Flashcard, "id" | "question" | "answer" | "state">;

/**
 * DTO for a flashcard presented during a study session.
 * Used in the response of `GET /api/flashcards/study/random`.
 */
export type StudyFlashcardDto = Pick<Flashcard, "id" | "question" | "answer">;

// --- Command Models ---

/**
 * Command model for creating a new flashcard.
 * Used as the request payload for `POST /api/flashcards`.
 */
export type CreateFlashcardCommand = Pick<Flashcard, "question" | "answer">;
