/**
 * Represents the state of a flashcard in the learning lifecycle.
 * - `new`: The card has been created but not yet reviewed.
 * - `learning`: The card is actively being learned.
 * - `review`: The card is due for review.
 */
export type FlashcardState = "new" | "learning" | "review";

/**
 * Base interface for a flashcard, mirroring the `public.flashcards` table schema.
 */
export interface Flashcard {
	id: number;
	user_id: string;
	question: string;
	answer: string;
	due: string; // ISO 8601 date string
	stability: number;
	difficulty: number;
	lapses: number;
	state: FlashcardState;
}

/**
 * Data Transfer Object (DTO) for a flashcard that has been generated by the AI
 * but not yet saved to the database. It only contains the essential `question`
 * and `answer` pair.
 *
 * @see `POST /api/flashcards/generate`
 */
export type GeneratedFlashcardDto = Pick<Flashcard, "question" | "answer">;

/**
 * Command Model for creating a new flashcard. This is used in the request payload
 * when a user accepts a generated flashcard and saves it to their collection.
 *
 * @see `POST /api/flashcards`
 */
export type CreateFlashcardCommand = Pick<Flashcard, "question" | "answer">;

/**
 * Data Transfer Object (DTO) representing a complete flashcard. This is returned
 * when a new flashcard is successfully created.
 *
 * @see `POST /api/flashcards`
 */
export type FlashcardDto = Flashcard;

/**
 * Data Transfer Object (DTO) for a summarized view of a flashcard.
 * Used in lists where displaying the full flashcard data is not necessary.
 *
 * @see `GET /api/flashcards`
 */
export type FlashcardSummaryDto = Pick<
	Flashcard,
	"id" | "question" | "answer" | "state"
>;

/**
 * Data Transfer Object (DTO) for a random flashcard retrieved for a study session.
 *
 * @see `GET /api/flashcards/random`
 */
export type RandomFlashcardDto = Pick<
	Flashcard,
	"id" | "question" | "answer" | "state"
>;
